### ISSUE TITLE
How to set or use landmarks correctly ?

### ISSUE THREAD

**Issue by DavidSelem** [Noctem/pokeminer#1]
I tried to run it for the first time and it throws this in the console

```
Traceback (most recent call last):
  File "C:\Users\David\Desktop\pokeminerNcotme\landmarks.py", line 72, in query_location
    geo = nom.geocode(query=query, geometry='geojson').raw
AttributeError: 'NoneType' object has no attribute 'raw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "worker.py", line 22, in <module>
    import config
  File "C:\Users\David\Desktop\pokeminerNcotme\config.py", line 187, in <module>
    LANDMARKS.add('Rice Eccles Stadium', hashtags={'Utes'})
  File "C:\Users\David\Desktop\pokeminerNcotme\landmarks.py", line 192, in add
    landmark = Landmark(*args, **kwargs)
  File "C:\Users\David\Desktop\pokeminerNcotme\landmarks.py", line 27, in __init__
    self.query_location(query)
  File "C:\Users\David\Desktop\pokeminerNcotme\landmarks.py", line 75, in query_location
    raise FailedQuery('Query for ' + query + ' did not return results.')
landmarks.FailedQuery: Query for Rice Eccles Stadium CiudadDelCarmen did not return results.
```

Config.py

```

# It is recommended to store the LANDMARKS object in a pickle to reduce startup 
# time if you are using queries.
LANDMARKS = Landmarks(query_suffix=AREA_NAME)

# Landmarks to reference when Pokémon are nearby
# If no points are specified then it will query OpenStreetMap for the coordinates
# If 1 point is provided then it will use those coordinates but not create a shape
# If 2 points are provided it will create a rectangle with its corners at those points
# If 3 or more points are provided it will create a polygon with vertices at each point
# You can specify the string to search for on OpenStreetMap with the query parameter
# If no query or points is provided it will query with the name of the landmark (and query_suffix)
# Optionally provide a set of hashtags to be used for tweets about this landmark
# Use is_area for large neighborhoods or regions
# When selecting a landmark, non-areas will be chosen first if any are close enough
# the default phrase is 'in' for areas and 'at' for non-areas, but can be overriden for either.

# since no points or query is provided, the names provided will be queried and suffixed with AREA_NAME
LANDMARKS.add('Rice Eccles Stadium', hashtags={'Utes'})
LANDMARKS.add('the Salt Lake Temple', hashtags={'TempleSquare'})

# provide two corner points to create a square for this area
LANDMARKS.add('City Creek Center', points=((40.769210, -111.893901), (40.767231, -111.888275)), hashtags={'CityCreek'})

# provide a query that is different from the landmark name so that OpenStreetMap finds the correct one
LANDMARKS.add('the State Capitol', query='Utah State Capitol Building')

## area examples ##
# query using name, override the default area phrase so that it says 'at (name)' instead of 'in'
LANDMARKS.add('the University of Utah', hashtags={'Utes'}, phrase='at', is_area=True)
# provide corner points to create a polygon of the area since OpenStreetMap does not have a shape for it
LANDMARKS.add('Yalecrest', points=((40.750263, -111.836502), (40.750377, -111.851108), (40.751515, -111.853833), (40.741212, -111.853909), (40.741188, -111.836519)), is_area=True)

```

**Comment by Noctem** [comment]
So that error occurs if it is unable to find the landmark on Nominatim/OpenStreetMap.

The reason the example landmark for *Rice Eccles Stadium* is failing is because `LANDMARKS = Landmarks(query_suffix=AREA_NAME)`  is appending your area name *CiudadDelCarmen* to all queries, and *Rice Eccles Stadium* doesn't exist there (it works if the area is set to *Salt Lake City*). So try it with a location that exists in the city you'll be scanning.

You will also want to either add spaces to your `AREA_NAME` ("*Ciudad del Carmen*"), or change the `query_suffix` in `LANDMARKS = Landmarks(query_suffix=AREA_NAME)` since OpenStreetMaps will likely be confused by the lack of spaces. `query_suffixes` can also be omitted altogether, but they are useful for helping Nominatim find the correct location (rather than a similarly named location in another city). You can also manually set the `query` for an individual landmark if the name you want to use for it is different from its name on OpenStreetmaps. As demonstrated here:
```python
LANDMARKS.add('the State Capitol', query='Utah State Capitol Building')
```
If the item doesn't exist on OpenStreetMaps or has a different shape/location than you want to use, you can also manually define the points and it will skip querying Nominatim altogether, as demonstrated with these:
```python
LANDMARKS.add('Yalecrest', points=((40.750263, -111.836502), (40.750377, -111.851108), (40.751515, -111.853833), (40.741212, -111.853909), (40.741188, -111.836519)), is_area=True)
LANDMARKS.add('City Creek Center', points=((40.769210, -111.893901), (40.767231, -111.888275)), hashtags={'CityCreek'})
```
If you provide one set of coordinates it will use that single point, two sets will create a rectangle with corners at those coordinates, and more than two will create a polygon with a corner at each point.

What I do is use a separate script to create all the landmarks and dump them to a pickle, which I load in my config. This lets me test the landmark queries without running the entire program and eliminates having to query on each startup. You can use [this script](https://github.com/Noctem/pokeminer/blob/master/scripts/pickle_landmarks.example.py) to do that, and then replace all of the landmarks in your config with:
```python
import pickle
with open('landmarks.pickle', 'rb') as f:
    LANDMARKS = pickle.load(f)
```
