### ISSUE TITLE
Worker problem

### ISSUE THREAD

**Issue by m3g4mInD** [Noctem/pokeminer#19]
Hello,thanks for you great job but i have same issues:
 Now only this part make me nuts.
:/home/pokeminer# python3 worker.py
Traceback (most recent call last):
  File "worker.py", line 21, in <module>
    class Worker:
  File "worker.py", line 24, in Worker
    network_executor = ThreadPoolExecutor(config.NETWORK_THREADS)
AttributeError: module 'config' has no attribute 'NETWORK_THREADS'
 

THIS IS FIXED   :)
and if i try to run : python3 web.py
Traceback (most recent call last):
  File "web.py", line 81, in <module>
    manager.connect()
  File "/usr/local/lib/python3.6/multiprocessing/managers.py", line 489, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/local/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/local/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
UPDATE : I fix python3 web.py by edit in db.py 
Line 19: DB_ENGINE = 'mysql://user:password@localhost/pokeminer'
Thanks

**Comment by m3g4mInD** [comment]
I close because i have made a new install and fix some of my errors,now works  http://prntscr.com/dt52ce
