### ISSUE TITLE
TypeError appeared while updating spawns

### ISSUE THREAD

**Issue by brazgardian** [Noctem/pokeminer#316]
I suddenly get a TypeError with spawns. The below error repeats continuously in my scan.log. All workers stay on 'I' state. Any idea?

`[2017-07-03 17:03:27][    INFO][root] Starting up!
[2017-07-03 17:03:29][   ERROR][overseer] A wild TypeError appeared while updating spawns!
Traceback (most recent call last):
  File "C:\Users\garrick\Desktop\Monocle\monocle\overseer.py", line 331, in update_spawns
    await run_threaded(spawns.update)
  File "C:\Users\garrick\Desktop\Monocle\monocle\shared.py", line 80, in run_threaded
    return await LOOP.run_in_executor(x, cb, *args)
  File "C:\Python36\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\garrick\Desktop\Monocle\monocle\spawns.py", line 62, in update
    spawn_time = (spawn.despawn_time + 1800) % 3600
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'`

**Comment by brazgardian** [comment]
I have narrowed the issue down to this row  of my spawnpoints table, unfortunately I do not see anything wrong with it. For additional context, this is row 662 out of 1100. I am using MySQL 5.7.14 on Win7.

![table](https://user-images.githubusercontent.com/2932104/27809726-3c1b3d2a-6020-11e7-96c8-e067ed2f33b5.PNG)

I am using a polygon boundary (simple with 5 points), and I have verified that this spawnpoint does fall within the boundary. I have exported the sql files for broken and fixed tables, in case it is helpful.

[spawnpoints.zip](https://github.com/Noctem/Monocle/files/1120683/spawnpoints.zip)

Not sure of the root cause for this issue.
