### ISSUE TITLE
Raspberry Pi installation problems

### ISSUE THREAD

**Issue by baskettcase** [Noctem/pokeminer#321]
When I am installing requirements.txt I am getting this error, any ideas?

```
Collecting pogeo==0.3.* (from -r requirements.txt (line 8))
  Using cached pogeo-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7xdn5i8_/pogeo/setup.py", line 9, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7xdn5i8_/pogeo/
```
I am trying to install Cython, but so far it is hanging... or at least looks to be hanging. Im going to let it run through the night and get back to this issue, depending on how things go :) Thanks!

**Comment by Noctem** [comment]
Cython will no longer be required to build pogeo 0.4, which should be released soon. In the meantime, you can speed up the Cython installation by specifying `--no-cython-compile`, like so:
```bash
pip3 install cython --install-option="--no-cython-compile"
```

**Comment by baskettcase** [comment]
I woke up this morning and tried installing it the way you said, but looks like it must have succeeded installing last night. Now Im getting another problem and it doesn't look like I can figure out what I am able to do to fix it. It's basically choking on pogeo. 

```Installing collected packages: pogeo
  Running setup.py install for pogeo ... error
    Complete output from command /var/www/html/pogo/home/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-86_zub8t/pogeo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-35iiox2l-record/install-record.txt --single-version-externally-managed --compile --install-headers /var/www/html/pogo/home/venv/include/site/python3.6/pogeo:
    running install
    running build
    running build_ext
    building 'pogeo' extension
    creating build
    creating build/temp.linux-armv7l-3.6
    creating build/temp.linux-armv7l-3.6/geometry
    creating build/temp.linux-armv7l-3.6/geometry/base
    creating build/temp.linux-armv7l-3.6/geometry/strings
    creating build/temp.linux-armv7l-3.6/geometry/util
    creating build/temp.linux-armv7l-3.6/geometry/util/coding
    creating build/temp.linux-armv7l-3.6/geometry/util/math
    creating build/temp.linux-armv7l-3.6/geometry/util/math/exactfloat
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DS2_USE_EXACTFLOAT -DARCH_K8 -Igeometry -Igeometry/s2 -Igeometry/util/math -I/var/www/html/pogo/home/venv/include -I/usr/local/include/python3.6m -c pogeo.cpp -o build/temp.linux-armv7l-3.6/pogeo.o -Wno-ignore-qualifiers -fpermissive -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from geometry/base/basictypes.h:9:0,
                     from geometry/util/math/vector3.h:17,
                     from geometry/util/math/vector3-inl.h:29,
                     from pogeo.cpp:506:
    geometry/base/casts.h: In function ‘Dest bit_cast(const Source&)’:
    geometry/base/casts.h:163:16: warning: typedef ‘VerifySizesAreEqual’ locally defined but not used [-Wunused-local-typedefs]
       typedef char VerifySizesAreEqual [sizeof(Dest) == sizeof(Source) ? 1 : -1];
                    ^
    In file included from geometry/util/math/mathutil.h:24:0,
                     from geometry/util/math/vector3-inl.h:44,
                     from pogeo.cpp:506:
    geometry/util/math/mathlimits.h: At global scope:
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:163:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed char, unsigned char)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:163:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed char, unsigned char)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:163:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed char, unsigned char)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:163:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed char, unsigned char)
     ^
    geometry/util/math/mathlimits.h:135:28: error: the value of ‘MathLimits<signed char>::kPosMax’ is not usable in a constant expression
       static const Type kMax = kPosMax; \
                                ^
    geometry/util/math/mathlimits.h:163:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed char, unsigned char)
     ^
    geometry/util/math/mathlimits.h:133:21: note: ‘MathLimits<signed char>::kPosMax’ was not initialized with a constant expression
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                         ^
    geometry/util/math/mathlimits.h:163:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed char, unsigned char)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:164:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed short int, unsigned short int)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:164:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed short int, unsigned short int)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:164:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed short int, unsigned short int)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:164:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed short int, unsigned short int)
     ^
    geometry/util/math/mathlimits.h:135:28: error: the value of ‘MathLimits<short int>::kPosMax’ is not usable in a constant expression
       static const Type kMax = kPosMax; \
                                ^
    geometry/util/math/mathlimits.h:164:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed short int, unsigned short int)
     ^
    geometry/util/math/mathlimits.h:133:21: note: ‘MathLimits<short int>::kPosMax’ was not initialized with a constant expression
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                         ^
    geometry/util/math/mathlimits.h:164:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed short int, unsigned short int)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:165:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed int, unsigned int)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:165:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed int, unsigned int)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:165:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed int, unsigned int)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:165:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed int, unsigned int)
     ^
    geometry/util/math/mathlimits.h:135:28: error: the value of ‘MathLimits<int>::kPosMax’ is not usable in a constant expression
       static const Type kMax = kPosMax; \
                                ^
    geometry/util/math/mathlimits.h:165:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed int, unsigned int)
     ^
    geometry/util/math/mathlimits.h:133:21: note: ‘MathLimits<int>::kPosMax’ was not initialized with a constant expression
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                         ^
    geometry/util/math/mathlimits.h:165:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed int, unsigned int)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:166:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed long int, unsigned long int)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:166:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed long int, unsigned long int)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:166:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed long int, unsigned long int)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:166:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed long int, unsigned long int)
     ^
    geometry/util/math/mathlimits.h:135:28: error: the value of ‘MathLimits<long int>::kPosMax’ is not usable in a constant expression
       static const Type kMax = kPosMax; \
                                ^
    geometry/util/math/mathlimits.h:166:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed long int, unsigned long int)
     ^
    geometry/util/math/mathlimits.h:133:21: note: ‘MathLimits<long int>::kPosMax’ was not initialized with a constant expression
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                         ^
    geometry/util/math/mathlimits.h:166:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed long int, unsigned long int)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:167:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed long long int, unsigned long long int)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:167:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed long long int, unsigned long long int)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:167:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed long long int, unsigned long long int)
     ^
    geometry/util/math/mathlimits.h:97:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 2)) - 1) + (Type(1) << (sizeof(Type)*8 - 2)))
                                                                                   ^
    geometry/util/math/mathlimits.h:133:31: note: in expansion of macro ‘SIGNED_INT_MAX’
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:167:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed long long int, unsigned long long int)
     ^
    geometry/util/math/mathlimits.h:135:28: error: the value of ‘MathLimits<long long int>::kPosMax’ is not usable in a constant expression
       static const Type kMax = kPosMax; \
                                ^
    geometry/util/math/mathlimits.h:167:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed long long int, unsigned long long int)
     ^
    geometry/util/math/mathlimits.h:133:21: note: ‘MathLimits<long long int>::kPosMax’ was not initialized with a constant expression
       static const Type kPosMax = SIGNED_INT_MAX(Type); \
                         ^
    geometry/util/math/mathlimits.h:167:1: note: in expansion of macro ‘DECL_SIGNED_INT_LIMITS’
     DECL_SIGNED_INT_LIMITS(signed long long int, unsigned long long int)
     ^
    geometry/util/math/mathlimits.h:103:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 1)) - 1) + (Type(1) << (sizeof(Type)*8 - 1)))
                                                                                   ^
    geometry/util/math/mathlimits.h:153:31: note: in expansion of macro ‘UNSIGNED_INT_MAX’
       static const Type kPosMax = UNSIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:168:1: note: in expansion of macro ‘DECL_UNSIGNED_INT_LIMITS’
     DECL_UNSIGNED_INT_LIMITS(unsigned char)
     ^
    geometry/util/math/mathlimits.h:103:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 1)) - 1) + (Type(1) << (sizeof(Type)*8 - 1)))
                                                                                   ^
    geometry/util/math/mathlimits.h:153:31: note: in expansion of macro ‘UNSIGNED_INT_MAX’
       static const Type kPosMax = UNSIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:168:1: note: in expansion of macro ‘DECL_UNSIGNED_INT_LIMITS’
     DECL_UNSIGNED_INT_LIMITS(unsigned char)
     ^
    geometry/util/math/mathlimits.h:103:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 1)) - 1) + (Type(1) << (sizeof(Type)*8 - 1)))
                                                                                   ^
    geometry/util/math/mathlimits.h:153:31: note: in expansion of macro ‘UNSIGNED_INT_MAX’
       static const Type kPosMax = UNSIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:168:1: note: in expansion of macro ‘DECL_UNSIGNED_INT_LIMITS’
     DECL_UNSIGNED_INT_LIMITS(unsigned char)
     ^
    geometry/util/math/mathlimits.h:103:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 1)) - 1) + (Type(1) << (sizeof(Type)*8 - 1)))
                                                                                   ^
    geometry/util/math/mathlimits.h:153:31: note: in expansion of macro ‘UNSIGNED_INT_MAX’
       static const Type kPosMax = UNSIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:168:1: note: in expansion of macro ‘DECL_UNSIGNED_INT_LIMITS’
     DECL_UNSIGNED_INT_LIMITS(unsigned char)
     ^
    geometry/util/math/mathlimits.h:155:28: error: the value of ‘MathLimits<unsigned char>::kPosMax’ is not usable in a constant expression
       static const Type kMax = kPosMax; \
                                ^
    geometry/util/math/mathlimits.h:168:1: note: in expansion of macro ‘DECL_UNSIGNED_INT_LIMITS’
     DECL_UNSIGNED_INT_LIMITS(unsigned char)
     ^
    geometry/util/math/mathlimits.h:153:21: note: ‘MathLimits<unsigned char>::kPosMax’ was not initialized with a constant expression
       static const Type kPosMax = UNSIGNED_INT_MAX(Type); \
                         ^
    geometry/util/math/mathlimits.h:168:1: note: in expansion of macro ‘DECL_UNSIGNED_INT_LIMITS’
     DECL_UNSIGNED_INT_LIMITS(unsigned char)
     ^
    geometry/util/math/mathlimits.h:103:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 1)) - 1) + (Type(1) << (sizeof(Type)*8 - 1)))
                                                                                   ^
    geometry/util/math/mathlimits.h:153:31: note: in expansion of macro ‘UNSIGNED_INT_MAX’
       static const Type kPosMax = UNSIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:169:1: note: in expansion of macro ‘DECL_UNSIGNED_INT_LIMITS’
     DECL_UNSIGNED_INT_LIMITS(unsigned short int)
     ^
    geometry/util/math/mathlimits.h:103:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 1)) - 1) + (Type(1) << (sizeof(Type)*8 - 1)))
                                                                                   ^
    geometry/util/math/mathlimits.h:153:31: note: in expansion of macro ‘UNSIGNED_INT_MAX’
       static const Type kPosMax = UNSIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:169:1: note: in expansion of macro ‘DECL_UNSIGNED_INT_LIMITS’
     DECL_UNSIGNED_INT_LIMITS(unsigned short int)
     ^
    geometry/util/math/mathlimits.h:103:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 1)) - 1) + (Type(1) << (sizeof(Type)*8 - 1)))
                                                                                   ^
    geometry/util/math/mathlimits.h:153:31: note: in expansion of macro ‘UNSIGNED_INT_MAX’
       static const Type kPosMax = UNSIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:169:1: note: in expansion of macro ‘DECL_UNSIGNED_INT_LIMITS’
     DECL_UNSIGNED_INT_LIMITS(unsigned short int)
     ^
    geometry/util/math/mathlimits.h:103:79: warning: overflow in constant expression [-fpermissive]
       (((Type(1) << (sizeof(Type)*8 - 1)) - 1) + (Type(1) << (sizeof(Type)*8 - 1)))
                                                                                   ^
    geometry/util/math/mathlimits.h:153:31: note: in expansion of macro ‘UNSIGNED_INT_MAX’
       static const Type kPosMax = UNSIGNED_INT_MAX(Type); \
                                   ^
    geometry/util/math/mathlimits.h:169:1: note: in expansion of macro ‘DECL_UNSIGNED_INT_LIMITS’
     DECL_UNSIGNED_INT_LIMITS(unsigned short int)
     ^
    geometry/util/math/mathlimits.h:155:28: error: the value of ‘MathLimits<short unsigned int>::kPosMax’ is not usable in a constant expression
       static const Type kMax = kPosMax; \
                                ^
    geometry/util/math/mathlimits.h:169:1: note: in expansion of macro ‘DECL_UNSIGNED_INT_LIMITS’
     DECL_UNSIGNED_INT_LIMITS(unsigned short int)
     ^
    geometry/util/math/mathlimits.h:153:21: note: ‘MathLimits<short unsigned int>::kPosMax’ was not initialized with a constant expression
       static const Type kPosMax = UNSIGNED_INT_MAX(Type); \
                         ^
    geometry/util/math/mathlimits.h:169:1: note: in expansion of macro ‘DECL_UNSIGNED_INT_LIMITS’
     DECL_UNSIGNED_INT_LIMITS(unsigned short int)
     ^
    cc1plus: warning: unrecognized command line option "-Wno-ignore-qualifiers"
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/var/www/html/pogo/home/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-86_zub8t/pogeo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-35iiox2l-record/install-record.txt --single-version-externally-managed --compile --install-headers /var/www/html/pogo/home/venv/include/site/python3.6/pogeo" failed with error code 1 in /tmp/pip-build-86_zub8t/pogeo/
```

**Comment by baskettcase** [comment]
I see.. I went and looked at your github page for pogeo https://github.com/Noctem/pogeo and it looks like it's a Cython extension, so maybe this will be fixed when Cython is no longer required?

**Comment by GCHarald** [comment]
Is there any solution for this, because I have the same problem when I try to install pogeo

`pip3 install pogeo`

In additon to the error message @baskettcase I get this:

`Command "/usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ki85ehue/pogeo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5i2uqdhc-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ki85ehue/pogeo/`

Any ideas?

**Comment by GCHarald** [comment]
I solved it.

First I installed pogeo local into the folder ~/pogeo
`git clone recursive https://github.com/Noctem/pogeo.git`
than I went to the Monocle folder and installed the module from the local git
`cd ~/Monocle`
`pip3 install --no-index --find-links -e ~/pogeo`

**Comment by ultrafunkamsterdam** [comment]
dont forget to modify the 3 lines in pogeo as stated in the wiki ('install on raspberry pi' link on the right)

**Comment by baskettcase** [comment]
So this doesn't seem to work anymore with Raspbian "Stretch" Im constantly getting the error that @GCHarald was getting. I even modified the file that @ultrafunkamsterdam mentioned and tried.. still similar errors. Except with this instead of gcc it says g++-6 failed. Since I git cloned pogeo instead of cc1plus it's giving warnings on adler32 uLong, etc. Any ideas of what I should try next?
