### ISSUE TITLE
Worker Exceptions

### ISSUE THREAD

**Issue by rileypool** [Noctem/pokeminer#327]
I've been getting countless EXCEPTIONS from my workers over the past week.  I'm getting these EXCEPTIONS in every instance that I'm running.  Is there any way to troubleshoot this issue?

![exceptions](https://user-images.githubusercontent.com/30186147/28229983-b6502960-68aa-11e7-81a4-29cf606f7789.jpg)

After double checking everything before making this post I checked the scan.log file and this is what I'm seeing.

[2017-07-14 15:34:47][   ERROR][worker-24] A wild AttributeError appeared!
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Monocle7\monocle\worker.py", line 649, in visit
    return await self.visit_point(point, spawn_id, bootstrap)
  File "C:\Users\Administrator\Desktop\Monocle7\monocle\worker.py", line 857, in visit_point
    if self.notifier.raid_eligible(normalized_raid):
  File "C:\Users\Administrator\Desktop\Monocle7\monocle\notification.py", line 800, in raid_eligible
    if (raidinfo.HasField('pokemon_id')):
AttributeError: 'dict' object has no attribute 'HasField'

**Comment by DavePlater** [comment]
Are you up to date with monocle and the requirements.txt?
