### ISSUE TITLE
Issues with pip3 install -r requirements.txt step

### ISSUE THREAD

**Issue by joesweats** [Noctem/pokeminer#329]
I keep receiving this error when trying to complete the pip3 install -r requirements.txt step:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 274, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1632, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/usr/lib/python3/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2793, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2697, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ("Expected ',' or end-of-list in", 'pogeo==0.3.*,', 'at', '*,')

Storing debug log for failure in /root/.pip/pip.log

I pulled the monocle repository today and just finished reinstalling python completely. No change in the error.

**Comment by janriecarlostidres** [comment]
I have de same error and don't know resolve to.
:(

**Comment by M3G4THEKING** [comment]
@joesweats  @janriecarlostidres   on a clean install ubuntu 14.04  
apt-get update
apt-get install build-essential libssl-dev libssl1.0.0 libgeos-c1
wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tgz
tar xvf Python-3.6.0.tgz
cd Python-3.6.0
./configure --enable-optimizations
make
make altinstall
apt-get install libmysqlclient-dev 
pip3.6 install ConfigParser
pip3.6 install mysqlclient
apt-get install mysql-server mysql-client
apt-get install apache2
apt-get install php5 libapache2-mod-php5
service apache2 restart
apt-get install php5-mysql php5-curl php5-gd php5-intl php-pear php5-imagick php5-imap php5-mcrypt php5-memcache php5-ming php5-ps php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl
service apache2 restart
apt-get install phpmyadmin
go to  http://IP/phpmyadmin/ creat a db and user
cd /home/
git clone --recursive https://github.com/Noctem/Monocle.git
make your changes on config.py the db and user 

#DB_ENGINE = 'sqlite:///db.sqlite'
DB_ENGINE = 'mysql://user:pass@localhost/db'
#DB_ENGINE = 'postgresql://user:pass@localhost/monocle

pip3.6 install -r requirements.txt
pip3.6 install -r optional-requirements.txt
python3.6 scripts/create_db.py
run your scan 
python3.6 scan.py --bootstrap

**Comment by DavePlater** [comment]
There was an old copy of requirements.txt that had an invalid character at that line.
If you get an updated copy it should be fine.
