### ISSUE TITLE
Hash key error

### ISSUE THREAD

**Issue by ewigg** [Noctem/pokeminer#335]
I have set the hash key in the config but I get this error.

```
Traceback (most recent call last):
  File "/home/david/Monocle/monocle/sanitized.py", line 268, in __getattr__
    default = _defaults.pop(name)
KeyError: 'HASH_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scan.py", line 218, in <module>
    main()
  File "scan.py", line 205, in main
    activate_hash_server(conf.HASH_KEY)
  File "/home/david/Monocle/monocle/sanitized.py", line 276, in __getattr__
    raise AttributeError(err)
AttributeError: HASH_KEY not in config, and no default has been set.
```

Using Bossland hash key.

**Comment by ewigg** [comment]
Solved. 

Moved the "config.py" to /monocle and it worked.
