### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by baskettcase** [Noctem/pokeminer#41]
(venv) bash-3.2$ python3 ./web.py
Traceback (most recent call last):
  File "./web.py", line 90, in <module>
    manager.connect()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/managers.py", line 489, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

I can't tell which file or directory it is looking for, since python error messages are not my thing.

**Comment by m3g4mInD** [comment]
@baskettcase  Try    python3  web.py -H localhost  -P 5000

**Comment by baskettcase** [comment]
Same error @m3g4mInD

**Comment by m3g4mInD** [comment]
@baskettcase  before python3 web.py -H your IP  -P 5000,you need to run python3 scan.py

**Comment by baskettcase** [comment]
Thanks heading to bed and I'll try this tomorrow. Thanks!

**Comment by baskettcase** [comment]
File "scan.py", line 26, in <module>
    raise ImportError('Please copy config.example.py to config.py and customize it.') from e
ImportError: Please copy config.example.py to config.py and customize it.

I already did this.. do I need to specify where it is found? is there a switch for that?

**Comment by baskettcase** [comment]
Ok got past this since I didn't realize you needed to put config.py into the pokeminer/pokeminer directory. I thought it was in the main working directory where the config.example.py was. Ill close this and Im still trying to get past the geos problem on both OS X and CentOS 6 now, which I have open in another issue thread. Thanks for the help!
