### ISSUE TITLE
UnboundLocalError: local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by baskettcase** [Noctem/pokeminer#55]
my scan.log has lots of these inside of it.. 

[2017-01-23 15:46:03,975][   ERROR][worker-14] A wild exception appeared!
Traceback (most recent call last):
  File "/path/to/pokeminer/pokeminer/worker.py", line 533, in visit
    return await self.visit_point(point, bootstrap=bootstrap)
  File "/path/to/pokeminer/pokeminer/worker.py", line 630, in visit_point
    responses = await self.call(request)
  File "/path/to/pokeminer/pokeminer/worker.py", line 475, in call
    if not response:
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by Noctem** [comment]
Thanks, fixed.

**Comment by LabSen** [comment]
I have the "same" error

[2017-02-03 07:20:17,519][   ERROR][worker-126] Exception during encounter.
Traceback (most recent call last):
  File "/home/Monocle/monocle/worker.py", line 536, in call
    if not response:
UnboundLocalError: local variable 'response' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Monocle/monocle/worker.py", line 765, in visit_point
    normalized.update(await self.encounter(pokemon))
  File "/home/Monocle/monocle/worker.py", line 922, in encounter
    responses = await self.call(request, action=2.25)
  File "/home/Monocle/monocle/worker.py", line 539, in call
    raise MaxRetriesException
monocle.worker.MaxRetriesException
[2017-02-03 07:20:53,398][ WARNING][worker-138] Hit the maximum number of attempt retries.

**Comment by Noctem** [comment]
@LabSen a8617f7 should fix that.
