### ISSUE TITLE
Can't complete Tutorial

### ISSUE THREAD

**Issue by steffenkopa** [Noctem/pokeminer#60]
```
[2017-01-25 19:09:32,962][   ERROR][worker-10] A wild exception appeared!
Traceback (most recent call last):
  File "/home/pokeminer/pokeminer/worker.py", line 587, in visit
    if not await self.login():
  File "/home/pokeminer/pokeminer/worker.py", line 183, in login
    await self.app_simulation_login(version)
  File "/home/pokeminer/pokeminer/worker.py", line 295, in app_simulation_login
    tutorial_state is not None and
UnboundLocalError: local variable 'tutorial_state' referenced before assignment
```

**Comment by Noctem** [comment]
Fixed in 6b5696d.
